# Generated by Django 4.2.3 on 2024-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0006_data_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="storename",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelName", models.CharField(max_length=100)),
            ],
        ),
    ]
