# Generated by Django 4.2.3 on 2024-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0007_storename"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="week",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
