# Generated by Django 4.2.3 on 2024-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0008_data_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="delflg",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="standard_data",
            name="delflg",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storename",
            name="delflg",
            field=models.BooleanField(default=False),
        ),
    ]
